import type { MarketConfig } from "@/lib/markets/types";

export const usConfig: MarketConfig = {
  market: "US",
  name: "EasyTeamPlan",
  wordmark: { first: "easy", second: "teamplan" },
  logoAriaLabel: "EasyTeamPlan Home",
  tagline: "Staff scheduling, time tracking, and PTO for US small businesses",
  title: "Employee Scheduling Software for US Small Businesses",
  description:
    "Employee and staff scheduling software for US small businesses. Build shifts, track hours and PTO, manage requests, and replace spreadsheets.",
  leadDescription:
    "Build shift schedules with drag-and-drop, manage time-off and availability requests, and keep overtime and hours in check — all in one modern cloud app your team can use on any phone.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.easyteamplan.com",
  contactEmail: "hello@easyteamplan.com",
  formspreeEndpoint: process.env.NEXT_PUBLIC_FORMSPREE_ENDPOINT ?? "",
  source: "easyteamplan.com",
  locale: "en_US",
  htmlLang: "en-US",
  inLanguage: "en-US",
  areaServedCountry: "United States",
  currency: "USD",
  nav: [
    { label: "Features", href: "/#features" },
    { label: "How it works", href: "/#how-it-works" },
    { label: "Time tracking", href: "/#time-tracking" },
    { label: "Pricing", href: "/#pricing" },
    { label: "FAQ", href: "/#faq" },
  ],
  footerNav: [
    { label: "FAQ", href: "/faq" },
    { label: "Pricing", href: "/pricing" },
    { label: "Privacy Policy", href: "/privacy-policy" },
    { label: "Terms", href: "/terms" },
  ],
  footerNote: "Built for US teams",
  keywords: [
    "employee scheduling software",
    "staff scheduling software",
    "shift scheduling software",
    "team scheduling software",
    "small business scheduling software",
    "work schedule maker",
    "employee schedule maker",
    "employee scheduling app",
    "time tracking software",
    "PTO tracking",
    "restaurant employee scheduling",
    "retail employee scheduling",
    "Fair Workweek compliance software",
    "predictive scheduling software",
  ],
  og: {
    alt: "EasyTeamPlan – Employee scheduling software for US small businesses",
    brand: "EasyTeamPlan",
    title: "Employee scheduling software for US small businesses",
    subtitle: "Scheduling, time tracking, and PTO in one app — built for US labor rules",
  },
};
